[package]
name = "neo"
description = "A new package manager for Nim with an intelligible codebase"
version = "0.1.8"
license = "BSD-3-Clause"
kind = "Binary"
backend = "C"
binaries = ["neo"]

[toolchain]
version = "2.2.0"

[dependencies]
semver = ">= 1.2.3"
jsony = ">= 1.1.5"
floof = ">= 1.0.0"
url = ">= 0.1.3"
shakar = ">= 0.1.3"
noise = ">= 0.1.10"
curly = ">= 1.1.1"
pretty = ">= 0.2.0"
crunchy = ">= 0.1.11"
parsetoml = ">= 0.7.2"
leveldb = ">= 0.4.1"
